name: Build Release APK

on:
  workflow_dispatch:

# 1. YE LINE BOHOT ZAROORI HAI - Ye server ki RAM limit badhati hai taaki OutOfMemoryError na aaye
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx5g -Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - uses: gradle/actions/setup-gradle@v3

    - name: Generate Fake Keystore
      run: |
        mkdir -p ~/.android
        keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"

    - name: Build Release APK with Fake (Debug) Key
      # 2. YAHAN END ME '-x lint' HAI taaki memory bach sake
      run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$HOME/.android/debug.keystore -Pandroid.injected.signing.store.password=android -Pandroid.injected.signing.key.alias=androiddebugkey -Pandroid.injected.signing.key.password=android -x lint

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-fake-signed
        # 3. Path update kiya h taaki kisi bhi folder me apk bane wo utha le
        path: app/build/outputs/apk/**/*.apk 
        if-no-files-found: error
        retention-days: 20
