name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - uses: gradle/actions/setup-gradle@v3

    - name: Build Release APK with Fake (Debug) Key
      # Ye command app ko Release mode me banayegi aur Android ke default fake key se sign karegi
      run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$HOME/.android/debug.keystore -Pandroid.injected.signing.store.password=android -Pandroid.injected.signing.key.alias=androiddebugkey -Pandroid.injected.signing.key.password=android

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-fake-signed
        # Path me thoda change kiya h taaki koi bhi apk bane wo properly pakad le
        path: app/build/outputs/apk/release/*.apk 
        if-no-files-found: error
        retention-days: 20
